### ISSUE TITLE
404 when using the "Back to the blog" feature

### ISSUE THREAD

**Issue by MozharAlhosni** [BlazorStatic/BlazorStaticMinimalBlog#2] opened 2024-03-13 00:03 UTC
When using the "Back to the blog" feature of any [post](https://tesar-tech.github.io/BlazorStaticMinimalBlog/blog/second-post), a 404 is returned:

![image](https://github.com/tesar-tech/BlazorStaticMinimalBlog/assets/109945717/da4fe107-1e67-4bd1-8bc6-4d1683bace6d)

![image](https://github.com/tesar-tech/BlazorStaticMinimalBlog/assets/109945717/1f2a604d-d390-447b-a3fd-3df8809c0f2a)

Most likely this is because https://github.com/tesar-tech/BlazorStatic/blob/f6178c9706dedb1c01814742654b4b768df3a6d8/src/BlazorStaticOptions.cs#L120 sets the default value to `blog`.

Also relevant is that https://github.com/tesar-tech/BlazorStaticMinimalBlog/blob/77acf4c9ca880a2e71d0b180a9a9dd6256db7860/Components/Pages/Blog.razor#L105 uses `BlogService.Options.BlogPageUrl`, which defaults to `blog`.

**Comment by tesar-tech** [comment] 2024-03-15 14:43
Thanks for letting me know and full explanation. It's fixed now. 

This is caused by the fact, that BlazorStatic was made to "host" blog not exactly be a blog, thus the unnecessary (in this case) `BlogUrl` option... The `/blog` is `/` home in blog...

I change the text to "back to home" and made the link empty.

**Closed as completed by tesar-tech** 2024-03-15 14:43 UTC
